################################################################
# This file contains the conda requirements for building the
# Trajectory Subsetter source code locally. See README.md for
# more information.
################################################################
name: trajectory-subsetter-local-dev
channels:
  - conda-forge
dependencies:
  - compilers
  - hdf5==1.14.2
  - boost-cpp==1.84.0
  - geotiff==1.7.1
  - cmake==3.30.3
  - gtest==1.15.2
