Identification: trajectorysubsetter_varinfo_config
Version: 1

# A list of hdf subdataset paths that provide the shortname value of the
# collection for the data file being processed.  Processed in this order to
# find a shortname value for the current file.
Collection_ShortName_Path:
  - '/HDF5_GLOBAL/short_name'
  - '/NC_GLOBAL/short_name'
  - '/Metadata/DatasetIdentification/shortName'
  - '/METADATA/DatasetIdentification/shortName'
  - '/Metadata/SeriesIdentification/shortName'
  - '/METADATA/SeriesIdentification/shortName'
  - '/HDF5_GLOBAL/id'
  - '/NC_GLOBAL/id'
  - 'short_name'
  - 'ShortName' # Required for MERRA-2

# A set of mission tagged shortname patterns defines a mission name for
# matching shortname values.
Mission:
  'GEDI_L4A': 'GEDI'


# Temporal subsetting typically encounters time tags in data files as
# e.g., delta_time, where the time value is relative to a "start-time"
# for the collection of datafiles, referred to as the time Epoch.
ProductEpochs:
  - Applicability:
      Mission: GEDI
    Epoch: '2018-01-01T00:00:00.000000'


# For cases where CF references do not exist, or are invalid
# These variables have no dimension references in the HDF5 file contents
CF_Overrides:
  - Applicability:
      Mission: 'GEDI'
      ShortNamePath: 'GEDI_L4A'
    Applicability_Group:
      - Applicability:
          Variable_Pattern: '/BEAM[\d]+/shot_number'
        Attributes:
          - Name: 'coordinates'
            Value: 'delta_time lat_lowestmode lon_lowestmode'

# For extending CF references. This allows for CF references to persist, while
# supplemental information is provided. In particular, e.g. for subsetting
# support, non-CF attributes can be provided.

CF_Supplements:
  - Applicability:
      Mission: 'GEDI'
      ShortNamePath: 'GEDI_L4A'
    Applicability_Group:
      - Applicability:
          Variable_Pattern: '/BEAM[\d]+/.*'
        Attributes:
          - Name: 'ancillary_variables'
            Value: 'shot_number'
  - Applicability:
      Mission: 'GEDI'
      ShortNamePath: 'GEDI_L[1234][AB]|GEDI0[1234]_[AB]'
    Global_Attributes:
      - Name: 'Data_Organization'
        Value: 'h5_trajectory'
    Applicability_Group:
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variable_Pattern: '/BEAM[\d]+/geolocation/'
        Attributes:
          # Resetting the spatial coordinates for subsetting purposes
          - Name: 'subset_control_variables'
            Value: 'delta_time, latitude_bin0, longitude_bin0'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      - Applicability:
          ShortNamePath: 'GEDI_L2A|GEDI02_A'
          Variable_Pattern: '/BEAM[\d]+/'
        Attributes:
          # Resetting the spatial coordinates for subsetting purposes
          - Name: 'subset_control_variables'
            Value: 'lat_lowestmode, lon_lowestmode, delta_time'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      - Applicability:
          ShortNamePath: 'GEDI_L2A|GEDI02_A'
          Variables: '/BEAM[\d]+/geolocation/'
        Attributes:
          # Resetting the spatial coordinates for subsetting purposes
          - Name: 'subset_control_variables'
            Value': 'lat_lowestmode, lon_lowestmode, delta_time'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      # Provide index segment subset-control designation for these dataset
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/rxwaveform'
        Attributes:
          - Name: 'subset_control_variables'
            Value: 'rx_sample_start_index, rx_sample_count'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/rx_sample_start_index'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variable_Pattern: '/BEAM[\\d]+/rx_sample_count'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/txwaveform'
        Attributes:
          - Name: 'subset_control_variables'
            Value: 'tx_sample_start_index, tx_sample_count'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/tx_sample_start_index'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variable_Pattern: '/BEAM[\\d]+/tx_sample_count'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
      - Applicability:
          ShortNamePath: 'GEDI_L2B|GEDI02_B'
          Variables: '/BEAM[\\d]+/pgap_theta_z'
        Attributes:
          - Name: 'subset_control_variables'
            Value: 'rx_sample_start_index, rx_sample_count'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'GEDI_L2B|GEDI02_B'
          Variables: '/BEAM[\\d]+/rx_sample_start_index'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'GEDI_L2B|GEDI02_B'
          Variable_Pattern: '/BEAM[\\d]+/rx_sample_count'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
