# This workflow will build the service, test and GoogleTest Docker images for
# the Harmony Trajectory Subsetter, then run the Python `unittest` suite and
# the C++ GoogleTest suite within those containers, reporting test results and
# code coverage as artefacts. It will be called by the workflow that run tests
# against new PRs and as a first step in the workflow that publishes new Docker
# images.
name: Run unit tests

on:
  workflow_call

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout harmony-trajectory-subsetter repository
        uses: actions/checkout@v5

      - name: Build service image
        run: ./bin/build-image

      - name: Build test image
        run: ./bin/build-test

      - name: Build GoogleTest image
        run: ./bin/build-gtest

      - name: Run test image
        run: ./bin/run-test

      - name: Run GoogleTest image
        run: ./bin/run-gtest

      - name: Archive test results and coverage
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**/*
