# This workflow will run when a PR is opened against the `main` branch. It will
# trigger the reusable workflow in `.github/workflows/run_tests.yml`, which
# builds the service, test and GoogleTest Docker images, and runs the Python
# and C++ unit test suites in containers built from those images.
name: Run unit tests for pull requests against main

on:
  pull_request:
    branches: [ main, '*feature*' ]

jobs:
  build_and_test:
    uses: ./.github/workflows/run_tests.yml
